name: Create tag
run-name: 'Create tag: ${{ github.event.commits[0].message }}'
on:
  push:
#    branches:
#      - main
#    paths:
#      - src/pycli/__init__.py

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Checkout repository
        uses: actions/checkout@v6
      - id: get_version
        run: echo "VERSION=$(hatch version)" | tee -a "$GITHUB_ENV" "$GITHUB_OUTPUT"
      - run: echo "VERSION:$VERSION"

  result:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - run: echo "VERSION:$VERSION"
        env:
          VERSION: ${{ needs.version.outputs.version }}
      - name: Create tag
        uses: actions/github-script@v5
        env:
          VERSION: ${{ needs.version.outputs.version }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/$VERSION",
              sha: context.sha
            })
